import json
from pathlib import Path


class DefectDojoExporter:

    SEVERITY_MAPPING = {
        "CRITICAL": "Critical",
        "HIGH": "High",
        "MEDIUM": "Medium",
        "LOW": "Low",
        "INFO": "Info"
    }

    def export(
        self,
        findings,
        output_file
    ):

        dojo_report = {
            "name": "AI-Triage Report",
            "type": "AI-Triage",
            "findings": []
        }

        for item in findings:

            result = item["result"]

            severity = self.SEVERITY_MAPPING.get(
                item.get(
                    "severity",
                    "LOW"
                ).upper(),
                "Low"
            )

            evidence = "\n".join(
                result.get(
                    "evidence",
                    []
                )
            )

            description = (
                f"Rule ID: {item.get('rule_id', '')}\n"
                f"File: {item.get('file_path', '')}\n"
                f"Line: {item.get('line', 0)}\n\n"
                f"Classification: "
                f"{result.get('classification')}\n"
                f"Confidence: "
                f"{result.get('confidence')}\n"
                f"Risk: "
                f"{result.get('risk')}\n\n"
                f"Reasoning:\n"
                f"{result.get('reasoning', '')}\n\n"
                f"Evidence:\n"
                f"{evidence}"
            )

            mitigation = (
                result.get(
                    "developer_recommendation",
                    ""
                )
            )

            finding = {
                "title": item.get(
                    "rule_id",
                    "AI-Triage Finding"
                ),
                "severity": severity,
                "description": description,
                "mitigation": mitigation,
                "impact": result.get(
                    "reasoning",
                    ""
                ),
                "references": (
                    "Generated by AI-Triage"
                ),
                "active": True,
                "verified": False,
                "false_p": (
                    result.get(
                        "classification"
                    )
                    == "Likely False Positive"
                ),
                "static_finding": True,
                "dynamic_finding": False
            }

            dojo_report[
                "findings"
            ].append(
                finding
            )

        Path(output_file).write_text(
            json.dumps(
                dojo_report,
                indent=2,
                ensure_ascii=False
            ),
            encoding="utf-8"
        )

        print(
            f"[INFO] DefectDojo export saved: "
            f"{output_file}"
        )